name: etl-env
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - click=7.1.2
  - colorama=0.4.4
  - cycler=0.10.0
  - decorator=4.4.2
  - flask=1.1.2
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - intel-openmp=2020.3
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - itsdangerous=1.1.0
  - jedi=0.17.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mkl=2018.0.3
  - msys2-conda-epoch=20160418
  - nbformat=5.1.2
  - nltk=3.5
  - numpy=1.14.2
  - olefile=0.46
  - openssl=1.1.1k
  - pandas=0.25.3
  - parso=0.8.1
  - pickleshare=0.7.5
  - pip=21.0.1
  - plotly=4.14.3
  - prompt-toolkit=3.0.8
  - pygments=2.8.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.6.3
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2021.1
  - pywin32=227
  - pyzmq=20.0.0
  - qt=5.9.7
  - regex=2021.3.17
  - retrying=1.3.3
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.11.1
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlalchemy=1.3.23
  - sqlite=3.35.2
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - anytree==2.8.0
    - treesource==0.0.6
